// <auto-generated />
using System;
using DeborahAccounting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeborahAccounting.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408063953_AddDoanhThuBanHang")]
    partial class AddDoanhThuBanHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeborahAccounting.Models.BBKK", b =>
                {
                    b.Property<string>("SoCT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayCT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKK1")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NguoiKK2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NguoiKK3")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("SoCT");

                    b.HasIndex("MaKho");

                    b.ToTable("BBKK");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTBBKK", b =>
                {
                    b.Property<string>("SoCT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaVT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("SoLuongKiemKe")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("SoCT", "MaVT");

                    b.HasIndex("MaVT");

                    b.ToTable("CTBBKK");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTGiamGia", b =>
                {
                    b.Property<string>("SoPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("SoPhieu", "MaHH");

                    b.HasIndex("MaHH");

                    b.ToTable("CTGiamGia");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTHoaDon", b =>
                {
                    b.Property<string>("SoHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("SoHD", "MaHH");

                    b.HasIndex("MaHH");

                    b.ToTable("CTHoaDon");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTPHIEUNX", b =>
                {
                    b.Property<string>("SoCT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaVT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("TKCo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TKNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("numeric(12,0)");

                    b.HasKey("SoCT", "MaVT");

                    b.HasIndex("MaVT");

                    b.ToTable("CTPHIEUNX");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTPhieu", b =>
                {
                    b.Property<string>("SoCT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TKNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TKCo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CTLQ")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric(12,0)");

                    b.HasKey("SoCT", "TKNo", "TKCo");

                    b.ToTable("CTPhieu");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTTraLai", b =>
                {
                    b.Property<string>("SoPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("SoPhieu", "MaHH");

                    b.HasIndex("MaHH");

                    b.ToTable("CTTraLai");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMBP", b =>
                {
                    b.Property<string>("MaBP")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TenBP")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaBP");

                    b.ToTable("DMBP");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMHH", b =>
                {
                    b.Property<string>("MaHH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dvt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenHH")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("MaHH");

                    b.ToTable("DMHH");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMKH", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoTKNH")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("MaKH");

                    b.ToTable("DMKH");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMKho", b =>
                {
                    b.Property<string>("MaKho")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaKho");

                    b.ToTable("DMKho");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMNCC", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaNCC");

                    b.ToTable("DMNCC");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMTK", b =>
                {
                    b.Property<string>("MaTK")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("CapTK")
                        .HasColumnType("int");

                    b.Property<string>("TKCapTren")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TenTK")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaTK");

                    b.ToTable("DMTK");
                });

            modelBuilder.Entity("DeborahAccounting.Models.DMVT", b =>
                {
                    b.Property<string>("MaVT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DVT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenVT")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaVT");

                    b.ToTable("DMVT");
                });

            modelBuilder.Entity("DeborahAccounting.Models.HDHH", b =>
                {
                    b.Property<string>("SoHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DienGiai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HTTT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayHD")
                        .HasColumnType("datetime2");

                    b.Property<string>("TKChietKhau")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKCoDoanhThu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKCoThue")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKNoThanhToan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ThueSuat")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("TienCK")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("TienDoanhThu")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("TienThanhToan")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("TienThue")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("TyLeCK")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("SoHD");

                    b.HasIndex("MaKH");

                    b.ToTable("HDHH");
                });

            modelBuilder.Entity("DeborahAccounting.Models.NguoiDung", b =>
                {
                    b.Property<string>("TenDN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("TenDN");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            TenDN = "admin",
                            MatKhau = "admin123",
                            Quyen = 1,
                            TenNguoiDung = "Quản trị viên"
                        });
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuGiamGia", b =>
                {
                    b.Property<string>("SoPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CTLQ")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienGiai")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayPhieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TKCo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKNoThue")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("numeric(18,0)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("SoPhieu");

                    b.HasIndex("MaKH");

                    b.ToTable("PhieuGiamGia");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuKT", b =>
                {
                    b.Property<string>("SoCT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CTLQ")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("NgayCT")
                        .HasColumnType("datetime2");

                    b.HasKey("SoCT");

                    b.ToTable("PhieuKT");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuNhapXuat", b =>
                {
                    b.Property<string>("SoCT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CTLQ")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayCT")
                        .HasColumnType("datetime2");

                    b.HasKey("SoCT");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaSP");

                    b.ToTable("PhieuNhapXuat");
                });

            modelBuilder.Entity("DeborahAccounting.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DeborahAccounting.Models.SoDuDauKy", b =>
                {
                    b.Property<string>("MaTK")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("DuCo")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("DuNo")
                        .HasColumnType("numeric(12,0)");

                    b.HasKey("MaTK");

                    b.ToTable("SoDuDauKy");
                });

            modelBuilder.Entity("DeborahAccounting.Models.TonDauKy", b =>
                {
                    b.Property<string>("MaVT")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaKho")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("numeric(12,0)");

                    b.HasKey("MaVT", "MaKho");

                    b.HasIndex("MaKho");

                    b.ToTable("TonDauKy");
                });

            modelBuilder.Entity("DeborahAccounting.Models.TraLai", b =>
                {
                    b.Property<string>("SoPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CTLQ")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienGiai")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKho")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayPhieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TKCo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TKNoThue")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("numeric(18,0)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("SoPhieu");

                    b.HasIndex("MaKH");

                    b.ToTable("TraLai");
                });

            modelBuilder.Entity("DeborahAccounting.Models.BBKK", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMKho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTBBKK", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMVT", "VatTu")
                        .WithMany()
                        .HasForeignKey("MaVT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.BBKK", "BienBanKK")
                        .WithMany("ChiTietBBKK")
                        .HasForeignKey("SoCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBanKK");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTGiamGia", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMHH", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.PhieuGiamGia", "Phieu")
                        .WithMany("ChiTietGiamGia")
                        .HasForeignKey("SoPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("Phieu");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTHoaDon", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMHH", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.HDHH", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("SoHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTPHIEUNX", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMVT", "VatTu")
                        .WithMany()
                        .HasForeignKey("MaVT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.PhieuNhapXuat", "PhieuNhapXuat")
                        .WithMany("ChiTietPhieuNX")
                        .HasForeignKey("SoCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapXuat");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTPhieu", b =>
                {
                    b.HasOne("DeborahAccounting.Models.PhieuKT", "PhieuKeToan")
                        .WithMany("ChiTietPhieu")
                        .HasForeignKey("SoCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuKeToan");
                });

            modelBuilder.Entity("DeborahAccounting.Models.CTTraLai", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMHH", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.TraLai", "PhieuTraLai")
                        .WithMany("ChiTietTraLai")
                        .HasForeignKey("SoPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuTraLai");
                });

            modelBuilder.Entity("DeborahAccounting.Models.HDHH", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMKH", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuGiamGia", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMKH", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuNhapXuat", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMKho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.DMNCC", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DeborahAccounting.Models.SoDuDauKy", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMTK", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DeborahAccounting.Models.TonDauKy", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMKho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeborahAccounting.Models.DMVT", "VatTu")
                        .WithMany()
                        .HasForeignKey("MaVT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DeborahAccounting.Models.TraLai", b =>
                {
                    b.HasOne("DeborahAccounting.Models.DMKH", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DeborahAccounting.Models.BBKK", b =>
                {
                    b.Navigation("ChiTietBBKK");
                });

            modelBuilder.Entity("DeborahAccounting.Models.HDHH", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuGiamGia", b =>
                {
                    b.Navigation("ChiTietGiamGia");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuKT", b =>
                {
                    b.Navigation("ChiTietPhieu");
                });

            modelBuilder.Entity("DeborahAccounting.Models.PhieuNhapXuat", b =>
                {
                    b.Navigation("ChiTietPhieuNX");
                });

            modelBuilder.Entity("DeborahAccounting.Models.TraLai", b =>
                {
                    b.Navigation("ChiTietTraLai");
                });
#pragma warning restore 612, 618
        }
    }
}
